### ISSUE TITLE
can't decrypt my ps4 save of borderlands 3

### ISSUE THREAD

**Issue by DarkG3n3sis** [bucanero/ps3-save-decrypters#5]
i don't know if i'm doing the right procedure, i did the clone of the repo, i created the executable with make and launched the command with -d and filename, but from Error: Please choose a Borderlands 3 PS4 file

**Comment by bucanero** [comment]
What is the file name you're trying to decrypt? It has to be a PS4 data file extracted on a jail broken console.

**Comment by DarkG3n3sis** [comment]
oh man, i don't have a jailbreak for ps4, there's no way apart from save wizard right? in any case sorry for the waste of time

**Comment by bucanero** [comment]
without jailbreak the only option is save wizard. 

This tool won't decrypt the console encryption.
