### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by nohn7** [bucanero/ps3-save-decrypters#6]
How do i run and can i encrypt the sample and resign it on savewizard to use on my ofw ps4

**Comment by bucanero** [comment]
which tool do you want to run? the PS4 decrypters I made require a jailbroken PS4 to access the plain save-game data files.

I don't have or use the Save Wizard tool so I don't know if the decrypters can be used with it or not. If you're using Save Wizard I think all the decryption and modifications are done by the SW tool.

**Comment by shulgovskiy** [comment]
Hello! Can anyone help me dencrypt the saves for Splinter Cell Blacklist?
